✨ feat: add support for multi-os tandem operations

diff --git a/intention b/intention
--- a/intention
+++ b/intention
@@ -72,8 +72,15 @@ is_procedure_available_linux() {
     return 1
 }
 
+is_procedure_available_tandem() {
+    [[ -f "${procedures}/${PROCEDURE}.ps1" && -f "${procedures}/${PROCEDURE}.sh" ]] && return 0
+    return 1
+}
+
 get_procedure_os() {
-    if is_procedure_available_windows; then
+    if is_procedure_available_tandem; then
+        echo "tandem"
+    elif is_procedure_available_windows; then
         echo "windows"
     elif is_procedure_available_linux; then
         echo "linux"
@@ -84,7 +91,9 @@ get_available_procedures() {
     local proc_files
     proc_files=$(ls "${procedures}")
     for file in $proc_files; do
-        if [[ $file == *.ps1 ]]; then
+        if [[ $file == *.ps1 && -f "${procedures}/${file%.ps1}.sh" ]]; then
+            echo -e "${file%.ps1}\tTandem"
+        elif [[ $file == *.ps1 ]]; then
             echo -e "${file%.ps1}\tWindows"
         elif [[ $file == *.sh ]]; then
             echo -e "${file%.sh}\tLinux"
@@ -160,24 +169,38 @@ fi
 
 # ACTION: run procedure
 OS=$(get_procedure_os)
-case "$OS" in
-"windows")
+
+run_windows() {
     echo "Rebooting to Windows and running procedure: $PROCEDURE"
     touch "${message_queue}/${PROCEDURE}"
     # eg $windows_title = 'Windows Boot Manager (on /dev/nvme0n1p1)'
     windows_title=$(sudo grep -i windows /boot/grub/grub.cfg | cut -d "'" -f 2)
     sudo grub-reboot "$windows_title"
     reboot
-    exit 0
-    ;;
-"linux")
+}
+
+run_linux() {
     bash "${procedures}/${PROCEDURE}.sh"
-    exit 0
-    ;;
-*)
-    echo "Error: Procedure '$PROCEDURE' is not available"
-    echo "Available procedures:"
-    get_available_procedures | sed 's/^/  - /'
-    exit 1
-    ;;
+}
+
+case "$OS" in
+    "tandem")
+        run_linux
+        run_windows
+        exit 0
+        ;;
+    "windows")
+        run_windows
+        exit 0
+        ;;
+    "linux")
+        run_linux
+        exit 0
+        ;;
+    *)
+        echo "Error: Procedure '$PROCEDURE' is not available"
+        echo "Available procedures:"
+        get_available_procedures | sed 's/^/  - /'
+        exit 1
+        ;;
 esac
